/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionapp;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import org.jfree.chart.axis.NumberAxis;

/**
 *
 * @author Laila
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        styleDashboard();
        chargerStatistiques();
        creerGraphique();
    }
private void chargerStatistiques(){
    EtudiantDAO dao = new EtudiantDAO();
    int total = dao.compterTous();
    int aujourdhui = dao.compterAujourdhui();
    
    lblTotal.setText(String.valueOf(total));
    lblAujourdhui.setText(String.valueOf(aujourdhui));
    
    int absencesAujourdhui = dao.computerAbsencesAujourdhui();
    lblAbsences.setText(String.valueOf(absencesAujourdhui));
    
    if(absencesAujourdhui > 0){
        NotificationService.afficherNotification("Alerte absences", absencesAujourdhui+" absence(s) enregistrée(s) aujourdhui !", NotificationService.AVERTISSEMENT);
    }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblAujourdhui = new javax.swing.JLabel();
        btnFermer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblAbsences = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 500));

        jLabel1.setText("Tableau de bord");

        jLabel2.setText("Total étudiants :");

        jLabel3.setText("Ajoutés aujourd'hui :");

        lblTotal.setText("0");

        lblAujourdhui.setText("0");

        btnFermer.setText("Fermer");
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });

        jLabel4.setText("Absences:");

        lblAbsences.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFermer)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTotal)
                                    .addComponent(lblAujourdhui)
                                    .addComponent(lblAbsences))))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTotal))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblAujourdhui))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblAbsences))
                .addGap(31, 31, 31)
                .addComponent(btnFermer)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnFermerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAbsences;
    private javax.swing.JLabel lblAujourdhui;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables

    private void styleDashboard() {
    setSize(800, 700);
    setTitle("Tableau de bord");
    setSize(800, 550);
    setLocationRelativeTo(null);
    setResizable(false);

    // Fond général
    getContentPane().setBackground(new java.awt.Color(240, 244, 248));

    // Header
    javax.swing.JPanel header = new javax.swing.JPanel();
    header.setBackground(new java.awt.Color(12, 31, 53));
    header.setPreferredSize(new java.awt.Dimension(800, 55));
    header.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 15));

    javax.swing.JLabel lblHeader = new javax.swing.JLabel("Tableau de bord");
    lblHeader.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
    lblHeader.setForeground(java.awt.Color.WHITE);
    header.add(lblHeader);

    javax.swing.JLabel lblDate = new javax.swing.JLabel(
        new java.text.SimpleDateFormat("EEEE dd MMMM yyyy",
            new java.util.Locale("fr", "FR")).format(new java.util.Date()));
    lblDate.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
    lblDate.setForeground(new java.awt.Color(133, 183, 235));
    header.add(lblDate);

    getContentPane().add(header, java.awt.BorderLayout.NORTH);

    // Panel des cartes statistiques
    javax.swing.JPanel cardsPanel = new javax.swing.JPanel();
    cardsPanel.setBackground(new java.awt.Color(240, 244, 248));
    cardsPanel.setLayout(new java.awt.GridLayout(1, 2, 20, 0));
    cardsPanel.setBorder(javax.swing.BorderFactory
        .createEmptyBorder(30, 40, 30, 40));

    // Carte Total étudiants
    javax.swing.JPanel card1 = creerCarte(
        "Total étudiants",
        String.valueOf(new EtudiantDAO().compterTous()),
        new java.awt.Color(24, 95, 165),
        new java.awt.Color(230, 241, 251));

    // Carte Absences aujourd'hui
    javax.swing.JPanel card2 = creerCarte(
        "Absences aujourd'hui",
        String.valueOf(new EtudiantDAO().computerAbsencesAujourdhui()),
        new java.awt.Color(226, 75, 74),
        new java.awt.Color(253, 235, 235));

    cardsPanel.add(card1);
    cardsPanel.add(card2);

    // Panel stats labels existants
    javax.swing.JPanel statsPanel = new javax.swing.JPanel();
    statsPanel.setBackground(new java.awt.Color(240, 244, 248));
    statsPanel.setLayout(new java.awt.GridBagLayout());

    java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
    gbc.insets = new java.awt.Insets(10, 20, 10, 20);
    gbc.gridx = 0; gbc.gridy = 0;

    
    // Bouton Fermer
    btnFermer.setBackground(new java.awt.Color(24, 95, 165));
    btnFermer.setForeground(java.awt.Color.WHITE);
    btnFermer.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
    btnFermer.setBorderPainted(false);
    btnFermer.setFocusPainted(false);
    btnFermer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnFermer.setPreferredSize(new java.awt.Dimension(120, 38));

    getContentPane().add(cardsPanel, java.awt.BorderLayout.CENTER);
}

private javax.swing.JPanel creerCarte(String titre, String valeur,
                                       java.awt.Color couleurAccent,
                                       java.awt.Color couleurFond) {
    javax.swing.JPanel carte = new javax.swing.JPanel();
    carte.setBackground(java.awt.Color.WHITE);
    carte.setLayout(new java.awt.BorderLayout());
    carte.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(
            new java.awt.Color(220, 230, 240), 1),
        javax.swing.BorderFactory.createEmptyBorder(20, 25, 20, 25)));

    // Bande colorée en haut
    javax.swing.JPanel topBand = new javax.swing.JPanel();
    topBand.setBackground(couleurAccent);
    topBand.setPreferredSize(new java.awt.Dimension(0, 5));
    carte.add(topBand, java.awt.BorderLayout.NORTH);

    // Contenu
    javax.swing.JPanel content = new javax.swing.JPanel();
    content.setBackground(java.awt.Color.WHITE);
    content.setLayout(new java.awt.BorderLayout());
    content.setBorder(javax.swing.BorderFactory
        .createEmptyBorder(15, 0, 10, 0));

    javax.swing.JLabel lblTitre = new javax.swing.JLabel(titre);
    lblTitre.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
    lblTitre.setForeground(new java.awt.Color(100, 120, 150));

    javax.swing.JLabel lblValeur = new javax.swing.JLabel(valeur);
    lblValeur.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 48));
    lblValeur.setForeground(couleurAccent);

    content.add(lblTitre, java.awt.BorderLayout.NORTH);
    content.add(lblValeur, java.awt.BorderLayout.CENTER);
    carte.add(content, java.awt.BorderLayout.CENTER);

    return carte;
}

private void creerGraphique() {
    // Récupère les données
    EtudiantDAO dao = new EtudiantDAO();
    java.util.Map<String, Integer> data = dao.absencesParJour();

    // Crée la série de données
    XYSeries serie = new XYSeries("Absences");

    if (data.isEmpty()) {
        // Données de démonstration si pas d'absences
        serie.add(1, 0);
        serie.add(2, 0);
        serie.add(3, 0);
    } else {
        int i = 1;
        for (java.util.Map.Entry<String, Integer> entry : data.entrySet()) {
            serie.add(i++, entry.getValue());
        }
    }

    XYSeriesCollection dataset = new XYSeriesCollection(serie);

    // Crée le graphique
    JFreeChart chart = ChartFactory.createXYLineChart(
        "Évolution des absences (7 derniers jours)",
        "Jours",
        "Nombre d'absences",
        dataset
    );

    // Personnalise le style
    chart.setBackgroundPaint(java.awt.Color.WHITE);
    chart.getTitle().setFont(
        new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
    chart.getTitle().setPaint(new java.awt.Color(12, 31, 53));

    // Légende
    chart.getLegend().setItemFont(
        new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 11));

    // Plot
    XYPlot plot = chart.getXYPlot();
    plot.setBackgroundPaint(new java.awt.Color(248, 251, 255));
    plot.setDomainGridlinePaint(new java.awt.Color(220, 230, 240));
    plot.setRangeGridlinePaint(new java.awt.Color(220, 230, 240));
    plot.setOutlinePaint(new java.awt.Color(220, 230, 240));

    // Style de la courbe
    XYLineAndShapeRenderer renderer = new XYLineAndShapeRenderer();
    renderer.setSeriesPaint(0, new java.awt.Color(24, 95, 165));
    renderer.setSeriesStroke(0, new java.awt.BasicStroke(
        2.5f,
        java.awt.BasicStroke.CAP_ROUND,
        java.awt.BasicStroke.JOIN_ROUND));
    renderer.setSeriesShapesVisible(0, true);
    renderer.setSeriesShape(0, new java.awt.geom.Ellipse2D.Double(
        -4, -4, 8, 8));
    renderer.setSeriesShapesFilled(0, true);
    plot.setRenderer(renderer);

    // Axes
    plot.getDomainAxis().setLabelFont(
        new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 11));
    plot.getDomainAxis().setTickLabelFont(
        new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 10));
    plot.getRangeAxis().setLabelFont(
        new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 11));
    plot.getRangeAxis().setTickLabelFont(
        new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 10));

    // Axe Y — valeurs entières uniquement
    ((NumberAxis) plot.getRangeAxis()).setStandardTickUnits(
        NumberAxis.createIntegerTickUnits());

    // Panel du graphique
    ChartPanel chartPanel = new ChartPanel(chart);
    chartPanel.setPreferredSize(new java.awt.Dimension(720, 300));
    chartPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(
            new java.awt.Color(220, 230, 240), 1),
        javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
    chartPanel.setBackground(java.awt.Color.WHITE);

    // Ajoute le graphique au Dashboard
    javax.swing.JPanel graphPanel = new javax.swing.JPanel(
        new java.awt.BorderLayout());
    graphPanel.setBackground(new java.awt.Color(240, 244, 248));
    graphPanel.setBorder(javax.swing.BorderFactory
        .createEmptyBorder(10, 20, 20, 20));
    graphPanel.add(chartPanel, java.awt.BorderLayout.CENTER);

    getContentPane().add(graphPanel, java.awt.BorderLayout.SOUTH);
}
}
