/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionapp;

/**
 *
 * @author Laila
 */
public class GestionAbsences extends javax.swing.JFrame {

    /**
     * Creates new form GestionAbsences
     */
    public GestionAbsences() {
        initComponents();
        styleAbsences();
        cmbEtudiant.removeAllItems();
        remplirComboEtudiants();
        chargerAbsences();
        
        txtDate.setText(new java.text.SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbEtudiant = new javax.swing.JComboBox<>();
        cmbStatut = new javax.swing.JComboBox<>();
        txtDate = new javax.swing.JTextField();
        txtMotif = new javax.swing.JTextField();
        btnFermer = new javax.swing.JButton();
        btnEnregistrer = new javax.swing.JButton();
        tableAbsenes = new javax.swing.JScrollPane();
        tableAbsences = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Etudiant :");

        jLabel2.setText("Date :");

        jLabel3.setText("Statut :");

        jLabel4.setText("Motif :");

        cmbEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEtudiantActionPerformed(evt);
            }
        });

        cmbStatut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "absent", "présent", "retard", "justifié" }));
        cmbStatut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatutActionPerformed(evt);
            }
        });

        btnFermer.setText("Fermer");
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });

        btnEnregistrer.setText("Enregistrer");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        tableAbsences.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableAbsenes.setViewportView(tableAbsences);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbStatut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMotif, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 117, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnFermer)
                        .addGap(18, 18, 18)
                        .addComponent(btnEnregistrer))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(tableAbsenes, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtMotif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbStatut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFermer)
                    .addComponent(btnEnregistrer))
                .addGap(18, 18, 18)
                .addComponent(tableAbsenes, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbStatutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatutActionPerformed

    private void cmbEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEtudiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEtudiantActionPerformed

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        // TODO add your handling code here:
        if(cmbEtudiant.getSelectedItem()==null){
            javax.swing.JOptionPane.showMessageDialog(this, "Sélectionnez un étudiant !","Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        String selected = cmbEtudiant.getSelectedItem().toString();
        int etudiantId = Integer.parseInt(selected.split(" - ")[0]);
        
        String date = txtDate.getText().trim();
        String[] statuts = {"absent", "présent", "retard", "justifié"};
int indexStatut = cmbStatut.getSelectedIndex();
String statut = (indexStatut >= 0) ? statuts[indexStatut] : "absent";
System.out.println("Index statut: " + indexStatut + " -> " + statut);
        String motif = txtMotif.getText().trim();
        
        if(date.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this,"La date est obligatoire !","Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        EtudiantDAO dao = new EtudiantDAO();
        System.out.println("=== VALEURS ENVOYÉES ===");
System.out.println("etudiantId = [" + etudiantId + "]");
System.out.println("date = [" + date + "]");
System.out.println("statut = [" + statut + "]");
System.out.println("motif = [" + motif + "]");
        dao.ajouterAbsence(etudiantId, date,statut, motif);
        
        NotificationService.afficherNotification("Absence enregistrée", "L'absence a été enregistrée pour le "+date,NotificationService.AVERTISSEMENT);
        
        txtMotif.setText("");
        chargerAbsences();
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnFermerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAbsences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAbsences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAbsences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAbsences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionAbsences().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JButton btnFermer;
    private javax.swing.JComboBox<String> cmbEtudiant;
    private javax.swing.JComboBox<String> cmbStatut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTable tableAbsences;
    private javax.swing.JScrollPane tableAbsenes;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtMotif;
    // End of variables declaration//GEN-END:variables

    private void remplirComboEtudiants() {
        EtudiantDAO dao = new EtudiantDAO();
        for (String[] e : dao.getEtudiantsPourCombo()){
            cmbEtudiant.addItem(e[0]+ " - "+ e[1]);
        }
    }

    private void remplirComboStatut() {
        cmbStatut.addItem("absent");
        cmbStatut.addItem("présent");
        cmbStatut.addItem("retard");
        cmbStatut.addItem("justifié");
    }

private void chargerAbsences() {
    javax.swing.table.DefaultTableModel model =
        new javax.swing.table.DefaultTableModel(
            new String[]{"ID", "Étudiant", "Date", "Statut", "Motif"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // tableau non éditable
            }
        };
    
    EtudiantDAO dao = new EtudiantDAO();
    java.util.List<String[]> liste = dao.lireAbsences();
    
    System.out.println("Nombre d'absences trouvées : " + liste.size());
    
    for (String[] abs : liste) {
        model.addRow(abs);
    }
    
    tableAbsences.setModel(model);
    tableAbsences.revalidate();
    tableAbsences.repaint();
}

    private void styleAbsences() {
    setTitle("Gestion des absences");
    setSize(900, 600);
    setLocationRelativeTo(null);

    // Fond général
    getContentPane().setBackground(new java.awt.Color(240, 244, 248));

    // Header
    javax.swing.JPanel header = new javax.swing.JPanel();
    header.setBackground(new java.awt.Color(12, 31, 53));
    header.setPreferredSize(new java.awt.Dimension(900, 55));
    header.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 15));

    javax.swing.JLabel lblHeader = new javax.swing.JLabel("Gestion des absences");
    lblHeader.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
    lblHeader.setForeground(java.awt.Color.WHITE);
    header.add(lblHeader);

    getContentPane().add(header, java.awt.BorderLayout.NORTH);

    // Style Labels
    java.awt.Color couleurLabel = new java.awt.Color(60, 80, 110);
    java.awt.Font fontLabel = new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12);
    for (java.awt.Component c : getContentPane().getComponents()) {
        if (c instanceof javax.swing.JLabel) {
            ((javax.swing.JLabel) c).setForeground(couleurLabel);
            ((javax.swing.JLabel) c).setFont(fontLabel);
        }
    }

    // Style ComboBox Etudiant
    cmbEtudiant.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
    cmbEtudiant.setBackground(java.awt.Color.WHITE);
    cmbEtudiant.setForeground(new java.awt.Color(30, 50, 80));
    cmbEtudiant.setBorder(javax.swing.BorderFactory.createLineBorder(
        new java.awt.Color(180, 200, 220), 1));
    cmbEtudiant.setPreferredSize(new java.awt.Dimension(200, 36));

    // Style ComboBox Statut
    cmbStatut.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
    cmbStatut.setBackground(java.awt.Color.WHITE);
    cmbStatut.setForeground(new java.awt.Color(30, 50, 80));
    cmbStatut.setBorder(javax.swing.BorderFactory.createLineBorder(
        new java.awt.Color(180, 200, 220), 1));
    cmbStatut.setPreferredSize(new java.awt.Dimension(150, 36));

    // Style champ Date
    txtDate.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
    txtDate.setBackground(java.awt.Color.WHITE);
    txtDate.setForeground(new java.awt.Color(30, 50, 80));
    txtDate.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(
            new java.awt.Color(180, 200, 220), 1),
        javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
    txtDate.setPreferredSize(new java.awt.Dimension(130, 36));

    // Style champ Motif
    txtMotif.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
    txtMotif.setBackground(java.awt.Color.WHITE);
    txtMotif.setForeground(new java.awt.Color(30, 50, 80));
    txtMotif.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(
            new java.awt.Color(180, 200, 220), 1),
        javax.swing.BorderFactory.createEmptyBorder(7, 10, 7, 10)));
    txtMotif.setPreferredSize(new java.awt.Dimension(160, 36));

    // Style tableau absences
    tableAbsences.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
    tableAbsences.setRowHeight(36);
    tableAbsences.setShowGrid(false);
    tableAbsences.setIntercellSpacing(new java.awt.Dimension(0, 0));
    tableAbsences.setSelectionBackground(new java.awt.Color(224, 236, 250));
    tableAbsences.setSelectionForeground(new java.awt.Color(12, 31, 53));
    tableAbsences.setBackground(java.awt.Color.WHITE);
    tableAbsences.setForeground(new java.awt.Color(40, 60, 90));

    tableAbsences.getTableHeader().setFont(
        new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
    tableAbsences.getTableHeader().setBackground(
        new java.awt.Color(240, 244, 248));
    tableAbsences.getTableHeader().setForeground(
        new java.awt.Color(80, 100, 130));
    tableAbsences.getTableHeader().setPreferredSize(
        new java.awt.Dimension(0, 38));
    tableAbsences.getTableHeader().setBorder(
        javax.swing.BorderFactory.createMatteBorder(
            0, 0, 2, 0, new java.awt.Color(24, 95, 165)));

    // Alternance couleurs lignes
    tableAbsences.setDefaultRenderer(Object.class,
        new javax.swing.table.DefaultTableCellRenderer() {
            public java.awt.Component getTableCellRendererComponent(
                    javax.swing.JTable table, Object value,
                    boolean isSelected, boolean hasFocus,
                    int row, int column) {
                super.getTableCellRendererComponent(
                    table, value, isSelected, hasFocus, row, column);
                setBorder(javax.swing.BorderFactory
                    .createEmptyBorder(0, 12, 0, 12));
                if (!isSelected) {
                    // Couleur selon statut
                    Object statut = table.getValueAt(row, 3);
                    if (statut != null) {
                        switch (statut.toString()) {
                            case "absent":
                                setBackground(new java.awt.Color(255, 245, 245));
                                break;
                            case "présent":
                                setBackground(new java.awt.Color(245, 255, 248));
                                break;
                            case "retard":
                                setBackground(new java.awt.Color(255, 252, 235));
                                break;
                            default:
                                setBackground(row % 2 == 0
                                    ? java.awt.Color.WHITE
                                    : new java.awt.Color(247, 250, 253));
                        }
                    }
                    setForeground(new java.awt.Color(40, 60, 90));
                }
                return this;
            }
        });

    // Bouton Enregistrer
    btnEnregistrer.setBackground(new java.awt.Color(24, 95, 165));
    btnEnregistrer.setForeground(java.awt.Color.WHITE);
    btnEnregistrer.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
    btnEnregistrer.setBorderPainted(false);
    btnEnregistrer.setFocusPainted(false);
    btnEnregistrer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnEnregistrer.setPreferredSize(new java.awt.Dimension(130, 36));

    // Bouton Fermer
    btnFermer.setBackground(new java.awt.Color(24, 95, 165));
    btnFermer.setForeground(java.awt.Color.WHITE);
    btnFermer.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
    btnFermer.setBorderPainted(false);
    btnFermer.setFocusPainted(false);
    btnFermer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btnFermer.setPreferredSize(new java.awt.Dimension(130, 36));
}
}
