/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionapp;

/**
 *
 * @author Laila
 */
public class ListeEtudiants extends javax.swing.JFrame {

    /**
     * Creates new form ListeEtudiants
     */
    public ListeEtudiants() {
        initComponents();
        styleListe();
        chargerDonnees();
    }
    public void chargerDonnees() {
         javax.swing.table.DefaultTableModel model = 
        new javax.swing.table.DefaultTableModel(
            new String[]{"ID", "Nom", "Prénom", "Email", "Téléphone"}, 0
        );
    
    EtudiantDAO dao = new EtudiantDAO();
    for (String[] etudiant : dao.lireTous()) {
        model.addRow(etudiant);
    }
    tableEtudiants.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableEtudiants = new javax.swing.JTable();
        btnFermer = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtRecherche = new javax.swing.JTextField();
        btnRecherche = new javax.swing.JButton();
        btnActualiser = new javax.swing.JButton();
        btnExportPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(800, 500));

        tableEtudiants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableEtudiants);

        btnFermer.setText("Fermer");
        btnFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermerActionPerformed(evt);
            }
        });

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        jLabel1.setText("Rechercher :");

        btnRecherche.setText("Rechercher");
        btnRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercheActionPerformed(evt);
            }
        });

        btnActualiser.setText("Actualiser");
        btnActualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualiserActionPerformed(evt);
            }
        });

        btnExportPDF.setText("Exporter PDF");
        btnExportPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExportPDF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModifier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSupprimer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecherche)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualiser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecherche)
                    .addComponent(btnActualiser))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFermer)
                    .addComponent(btnSupprimer)
                    .addComponent(btnModifier)
                    .addComponent(btnExportPDF))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFermerActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnFermerActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        // TODO add your handling code here:
        int ligne = tableEtudiants.getSelectedRow();
        if(ligne == -1){
            javax.swing.JOptionPane.showMessageDialog(this,"Sélectionnez un étudiant à supprimer");
            return;
        }
        int id = Integer.parseInt(tableEtudiants.getValueAt(ligne,0).toString());
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Confirmer la suppression?", "Attention", javax.swing.JOptionPane.YES_OPTION);
        
        if(confirm == javax.swing.JOptionPane.YES_OPTION){
            EtudiantDAO dao = new EtudiantDAO();
            dao.supprimer(id);
            chargerDonnees();
            NotificationService.afficherNotification("Etudiant supprimé", "L'étudiant a été supprimé de la base !", NotificationService.ERREUR);
        }
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
        int ligne = tableEtudiants.getSelectedRow();
        if (ligne == -1){
            javax.swing.JOptionPane.showMessageDialog(this, "Séléctionnez un étudiant à modiier");
            return;
        }
        String id = tableEtudiants.getValueAt(ligne, 0).toString();
        String nom = tableEtudiants.getValueAt(ligne, 1).toString();
        String prenom = tableEtudiants.getValueAt(ligne, 2).toString();
        String email = tableEtudiants.getValueAt(ligne, 3).toString();
        String tel = tableEtudiants.getValueAt(ligne, 4).toString();
        
        ModifierEtudiant form = new ModifierEtudiant();
        form.remplirChamps(id, nom, prenom, email, tel);
        form.setVisible(true);
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercheActionPerformed
        // TODO add your handling code here:
    String motCle = txtRecherche.getText().trim();
    
    javax.swing.table.DefaultTableModel model = 
        new javax.swing.table.DefaultTableModel(
            new String[]{"ID", "Nom", "Prénom", "Email", "Téléphone"}, 0
        );
    
    EtudiantDAO dao = new EtudiantDAO();
    java.util.List<String[]> liste;
    
    if (motCle.isEmpty()) {
        liste = dao.lireTous();
    } else {
        liste = dao.rechercher(motCle);
    }
    
    if (liste.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Aucun étudiant trouvé !",
            "Résultat",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    
    for (String[] etudiant : liste) {
        model.addRow(etudiant);
    }
    
    tableEtudiants.setModel(model);
        
    }//GEN-LAST:event_btnRechercheActionPerformed

    private void btnActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualiserActionPerformed
        // TODO add your handling code here:
        txtRecherche.setText("");
        chargerDonnees();
    }//GEN-LAST:event_btnActualiserActionPerformed

    private void btnExportPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportPDFActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.setDialogTitle("Enregistrer le PDF");
        fileChooser.setSelectedFile(new java.io.File("liste_etudiants.pdf"));
        
        int userSelection = fileChooser.showSaveDialog(this);
        if(userSelection != javax.swing.JFileChooser.APPROVE_OPTION) return;
        
        String cheminFichier = fileChooser.getSelectedFile().getAbsolutePath();
        if(!cheminFichier.endsWith(".pdf")) cheminFichier += ".pdf";
        
        try{
            com.itextpdf.text.Document document = new com.itextpdf.text.Document();
            com.itextpdf.text.pdf.PdfWriter.getInstance(document, new java.io.FileOutputStream(cheminFichier));
            document.open();
            
            com.itextpdf.text.Font titreFont = new com.itextpdf.text.Font(
               com.itextpdf.text.Font.FontFamily.HELVETICA, 18, 
               com.itextpdf.text.Font.BOLD);
            com.itextpdf.text.Paragraph titre = new com.itextpdf.text.Paragraph(
               "Liste des Etudiants\n\n", titreFont);  
            titre.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
            document.add(titre);
            
            com.itextpdf.text.pdf.PdfPTable table = new com.itextpdf.text.pdf.PdfPTable(5);
            table.setWidthPercentage(100);
            table.setWidths(new float[]{1f, 2f, 2f, 3f, 2f});
            
            String[] entetes = {"ID","Nom", "Prenom", "Email","Téléphone"};
            com.itextpdf.text.Font enteteFont = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 12,com.itextpdf.text.Font.BOLD);
            for(String entete : entetes){
                com.itextpdf.text.pdf.PdfPCell cell = new com.itextpdf.text.pdf.PdfPCell(new com.itextpdf.text.Phrase(entete,enteteFont));
                cell.setBackgroundColor(new com.itextpdf.text.BaseColor(52, 152, 219));
                cell.setHorizontalAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
                cell.setPadding(8);
                table.addCell(cell);
            }
            
            EtudiantDAO dao = new EtudiantDAO();
            for(String[] etudiant : dao.lireTous()){
                for(String valeur : etudiant){
                    com.itextpdf.text.pdf.PdfPCell cell = new com.itextpdf.text.pdf.PdfPCell(new com.itextpdf.text.Phrase(valeur != null ? valeur : ""));
                    cell.setPadding(6);
                    table.addCell(cell);
                }
            }
            document.add(table);
            
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("EEEE dd MMMM yyyy 'à' HH:mm", new java.util.Locale("fr", "FR"));
            document.add(new com.itextpdf.text.Paragraph("\nExporté le : " + sdf.format(new java.util.Date())));
            document.close();
            javax.swing.JOptionPane.showMessageDialog(this, "PDF exporté avec succès !\n" + cheminFichier,
            "Export réussi",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
             javax.swing.JOptionPane.showMessageDialog(this,
            "Erreur lors de l'export : " + e.getMessage(),
            "Erreur",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnExportPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListeEtudiants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListeEtudiants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListeEtudiants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListeEtudiants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListeEtudiants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualiser;
    private javax.swing.JButton btnExportPDF;
    private javax.swing.JButton btnFermer;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnRecherche;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEtudiants;
    private javax.swing.JTextField txtRecherche;
    // End of variables declaration//GEN-END:variables

    private void styleListe() {
        setTitle("Liste des étudiants");
        setSize(800,500);
        setLocationRelativeTo(null);
        
        getContentPane().setBackground(new java.awt.Color(240,244,248));
        
        javax.swing.JPanel header = new javax.swing.JPanel();
        header.setBackground(new java.awt.Color(12,31,53));
        header.setPreferredSize(new java.awt.Dimension(1024,55));
        header.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT,20,15));
        
        javax.swing.JLabel lblHeader = new javax.swing.JLabel("Liste des étudiants");
        lblHeader.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD,16));
        lblHeader.setForeground(java.awt.Color.WHITE);
        header.add(lblHeader);
        
        getContentPane().add(header, java.awt.BorderLayout.NORTH);
        
        tableEtudiants.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN,13));
        tableEtudiants.setRowHeight(38);
        tableEtudiants.setShowGrid(false);
        tableEtudiants.setIntercellSpacing(new java.awt.Dimension(0,0));
        tableEtudiants.setSelectionBackground(new java.awt.Color(224,236,250));
        tableEtudiants.setSelectionForeground(new java.awt.Color(12,31,53));
        tableEtudiants.setBackground(java.awt.Color.WHITE);
        tableEtudiants.setForeground(new java.awt.Color(40,60,90));
        
        tableEtudiants.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD,12));
        tableEtudiants.getTableHeader().setBackground(new java.awt.Color(240,244,248));
        tableEtudiants.getTableHeader().setForeground(new java.awt.Color(80,100,130));
        tableEtudiants.getTableHeader().setPreferredSize(new java.awt.Dimension(0,40));
        tableEtudiants.getTableHeader().setBorder(javax.swing.BorderFactory.createMatteBorder(0,0,2,0, new java.awt.Color(24,95,165)));
        
        tableEtudiants.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer(){
            public java.awt.Component getTableCellrendererComponent(javax.swing.JTable table, Object value, boolean isSelected, boolean hasFocus,int row,int column){
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                setBorder(javax.swing.BorderFactory.createEmptyBorder(0,12,0,12));
                if(!isSelected){
                    setBackground(row%2==0?java.awt.Color.WHITE :new java.awt.Color(247,250,253));
                    setForeground(new java.awt.Color(40,60,90));
                }
                return this;
            }
        });
        
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220,230,240),1));
        jScrollPane1.getViewport().setBackground(java.awt.Color.WHITE);
        
        styleBtn(btnModifier,new java.awt.Color(24,95,165),java.awt.Color.white);
        styleBtn(btnSupprimer, new java.awt.Color(226,75,74),java.awt.Color.WHITE);
        styleBtn(btnExportPDF, new java.awt.Color(29,158,117),java.awt.Color.WHITE);
        
        
        txtRecherche.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN,13));
        txtRecherche.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180,200,220),1),javax.swing.BorderFactory.createEmptyBorder(7,10,7,10)));
        txtRecherche.setPreferredSize(new java.awt.Dimension(220,36));
    }
    private void styleBtn(javax.swing.JButton btn,java.awt.Color bg,java.awt.Color fg){
        btn.setBackground(bg);
        btn.setForeground(fg);
        btn.setFont(new java.awt.Font("Segoe UI",java.awt.Font.PLAIN,12));
        btn.setBorderPainted(false);
        btn.setFocusPainted(false);
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn.setPreferredSize(new java.awt.Dimension(120,36));
    }
}
