/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionapp;

/**
 *
 * @author Laila
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        styleMainFrame();
        appliquerRole();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAccueil = new javax.swing.JButton();
        btnAjouter = new javax.swing.JButton();
        btnListe = new javax.swing.JButton();
        btnQuitter = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        btnDeconnexion = new javax.swing.JButton();
        btnAbsences = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAccueil.setText("Accueil");
        btnAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccueilActionPerformed(evt);
            }
        });

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnListe.setText("Liste");
        btnListe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeActionPerformed(evt);
            }
        });

        btnQuitter.setText("Quitter");
        btnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitterActionPerformed(evt);
            }
        });

        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnDeconnexion.setText("Déconnexion");
        btnDeconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeconnexionActionPerformed(evt);
            }
        });

        btnAbsences.setText("Absences");
        btnAbsences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbsencesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAccueil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnListe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAbsences, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDeconnexion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
            .addComponent(btnQuitter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(btnAccueil)
                .addGap(12, 12, 12)
                .addComponent(btnDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAjouter)
                .addGap(12, 12, 12)
                .addComponent(btnListe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAbsences)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeconnexion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuitter)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        // TODO add your handling code here:
        new AjouterEtudiant().setVisible(true);
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnListeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeActionPerformed
        // TODO add your handling code here:
        new ListeEtudiants().setVisible(true);
    }//GEN-LAST:event_btnListeActionPerformed

    private void btnAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccueilActionPerformed
        // TODO add your handling code here:
        javax.swing.JOptionPane.showMessageDialog(this, "Bienvenue dans GestionApp", "Accueil",javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAccueilActionPerformed

    private void btnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitterActionPerformed
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,"Voulez-vous vraiment quitter?", "Quitter", javax.swing.JOptionPane.YES_OPTION);
        if(confirm == javax.swing.JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnQuitterActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnDeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeconnexionActionPerformed
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Voulez-vous vous déconnecter?", "Déconnexion", javax.swing.JOptionPane.YES_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION){
            SessionUtilisateur.deconnecter();
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnDeconnexionActionPerformed

    private void btnAbsencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbsencesActionPerformed
        // TODO add your handling code here:
        new GestionAbsences().setVisible(true);
    }//GEN-LAST:event_btnAbsencesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbsences;
    private javax.swing.JButton btnAccueil;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDeconnexion;
    private javax.swing.JButton btnListe;
    private javax.swing.JButton btnQuitter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void appliquerRole() {
        if(!SessionUtilisateur.isAdmin()){
            btnAjouter.setEnabled(false);
            btnAjouter.setToolTipText("Accès réservé à l'administrateur");
        }
        setTitle("GestionApp - "+ SessionUtilisateur.getUsername() +" ("+ SessionUtilisateur.getRole()+")");
      
    }

    private void styleMainFrame() {
        setTitle("GestionApp — "+ SessionUtilisateur.getUsername());
        setSize(800, 500);
        setLocationRelativeTo(null);
        
        getContentPane().setBackground(new java.awt.Color(240,244,248));
        
        jPanel1.setBackground(new java.awt.Color(12,31,53));
        jPanel1.setBorder(null);
        
        javax.swing.JButton[] boutons = {
            btnAccueil, btnAjouter, btnListe, btnAbsences, btnDashboard, btnDeconnexion, btnQuitter
                
        };
        
        for(javax.swing.JButton btn : boutons){
            btn.setBackground(new java.awt.Color(12,31,53));
            btn.setForeground(new java.awt.Color(133,183,235));
            btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN,13));
            btn.setBorderPainted(false);
            btn.setFocusPainted(false);
            btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            
            btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent e){
                javax.swing.JButton b = (javax.swing.JButton) e.getSource();
                if(!b.equals(btnDeconnexion)){
                    b.setBackground(new java.awt.Color(24,47,80));
                }
            }
            public void mouseExited(java.awt.event.MouseEvent e){
                javax.swing.JButton b = (javax.swing.JButton) e.getSource();
                if(!b.equals(btnAccueil) && !b.equals(btnDeconnexion)){
                    b.setBackground(new java.awt.Color(12,31,53));
                }
            }
        });
        
    }
        btnAccueil.setBackground(new java.awt.Color(24,95,165));
        btnAccueil.setForeground(java.awt.Color.WHITE);
        btnAccueil.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD,13));
        
        btnDeconnexion.setForeground(new java.awt.Color(226,75,74));
        btnDeconnexion.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN,13));
        
        jPanel2.setBackground(new java.awt.Color(240,244,248));
        jPanel2.setBorder(null);
        
        javax.swing.JLabel lblBienvenue = new javax.swing.JLabel("Bienvenue, "+SessionUtilisateur.getUsername()+" !");
        lblBienvenue.setFont(new java.awt.Font("Segoe UI",java.awt.Font.BOLD,22));
        lblBienvenue.setForeground(new java.awt.Color(12,31,53));
        lblBienvenue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        javax.swing.JLabel lblSous = new javax.swing.JLabel("Sélectionnez une option dans le menu");
        lblSous.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN,14));
        lblSous.setForeground(new java.awt.Color(100, 130,160));
        lblSous.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        jPanel2.setLayout(new java.awt.GridBagLayout());
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx= 0;gbc.gridy=0;
        gbc.insets= new java.awt.Insets(0,0,8,0);
        jPanel2.add(lblBienvenue,gbc);
        gbc.gridy=1;
        jPanel2.add(lblSous, gbc);
       
        
        
}
}